name: mac_tsan_sectransport
on:
  push:
    paths-ignore:
    - 'docs/**'

jobs:
  mac_tsan_sectransport:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: make test_tsan_sectransport
      run: make -f makefile.dev test_tsan_sectransport
